#  Template React Deploy

#  This template allows you to deploy your React app to an AWS S3 bucket and invalidate the old AWS Cloudfront distribution.
#  The workflow allows running tests, code linting and security scans on feature branches (as well as master).
#  The react app will be validated, deployed to S3 and trigger an AWS Cloudfront distribution invalidation to refresh the CDN caches after the code is merged to master.

# Prerequisites: $AWS_ACCESS_KEY_ID, $AWS_SECRET_ACCESS_KEY setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's:
# README https://bitbucket.org/atlassian/aws-s3-deploy/src/master/README.md
# README https://bitbucket.org/atlassian/aws-cloudfront-invalidate/src/master/README.md

image: node:10.15.3

# Workflow Configuration

pipelines:
  default:
    - step:
        name: Build artifact
        script:
          - mkdir build
          - npm run build
        artifacts:
          - build/*
    - step:
        name: Deploy to Production
        deployment: Production
        trigger: automatic
        clone:
          enabled: false
        script:
          # sync your files to S3
          - pipe: atlassian/aws-s3-deploy:0.4.4
            variables:
              AWS_ACCESS_KEY_ID: "AKIA4JQIHVKGX2V2XDDU"
              AWS_SECRET_ACCESS_KEY: "JYNIFxTxokaLnerzu69CaWumkaFgEckc7PtzCR8U"
              AWS_DEFAULT_REGION: "ap-south-1"
              S3_BUCKET: "aws-s3-automation"
              LOCAL_PATH: "artifact"
