name: Deploy to EC2

on:
  push:
    branches:
      - app-v2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          #cache: "npm"
          #cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Run linting
        working-directory: ./app
        run: npm run lint

      - name: Build application
        working-directory: ./app
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/aws_s3_automation
            git fetch origin
            git checkout app-v2
            git pull origin app-v2
            cd app
            npm ci
            npm run lint
            npm run build
            chmod -R 755 dist
            sudo nginx -t
            sudo systemctl restart nginx
            echo "Deployment completed successfully!"
